### ISSUE TITLE
Change AuthServiceProxy to MoneroAuthServiceProxy 

### ISSUE THREAD

**Issue by escrowmycoinsnet** [XMRto/python-monerorpc#7]
Basically, **AuthServiceProxy** interferes with _python-bitcoinrpc_ one, so you cannot work with both, you just have to change it to **MoneroAuthServiceProxy** in order to make it work solely and avoid any problems with other service

**Comment by normoes** [comment]
I am not sure if I understand correctly.

If used in the same project I would group the functionalities in separate modules like:
* monero_stuff.py
* bitcoin_stuff.py

You wouldn't  have the problem then.

Apart from that you could deal with that when importing:
```
 from monerorpc.authproxy import MoneroAuthServiceProxy, MoneroJSONRPCException
 from bitcpoinrpc.authproxy import AuthServiceProxy, JSONRPCException
```
